### ISSUE TITLE
Подключение по IP теперь работает для всех серверов

### ISSUE THREAD

**Issue by u624ka** [xzfc/baka-extensions-tool#12]
На официальных серверах больше нет никаких дополнительных ключей для соединения. Теперь через connect("ws://12.345.678:9999", "") можно зайти на абсолютно любой сервер вне зависимости от режима, поэтому можно вместо протухающих ключей и морально устаревших команд для брутилки просто отсылать адреса.

**Comment by xzfc** [comment]
Отлично.
